//! Parser parity regression test. Locks the Rust port to the same results the
//! Python parser (`lit-bridge/parsers/claude/v2_1.py`) produces on its own validated
//! capture corpus. Fixtures copied from `lit-bridge/tests/captures/`.
//!
//! Expected values were generated by running the Python parser over these exact files
//! (see scripts/classify_all.py). If Anthropic changes the TUI and both parsers are
//! re-validated, regenerate these expectations.

use std::path::Path;

use lit_bridge_rs::parser::{select_parser, TuiParser};

/// (fixture, expected detect_state, expected count_assistant_messages)
const EXPECTED: &[(&str, &str, usize)] = &[
    ("claude_2.1.x_dialog.txt", "dialog", 0),
    ("claude_2.1.x_idle.txt", "idle", 1),
    ("claude_2.1.x_responding.txt", "responding", 4),
    ("claude_2.1.x_thinking.txt", "thinking", 1),
    ("claude_2.1.x_tool_use.txt", "idle", 2),
];

#[test]
fn parser_matches_python_oracle() {
    let parser = select_parser("claude-code").expect("claude-code parser");
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    for (file, exp_state, exp_count) in EXPECTED {
        let bytes = std::fs::read(dir.join(file)).expect("fixture present");
        let text = String::from_utf8_lossy(&bytes);
        let state = parser.detect_state(&text).as_str();
        let count = parser.count_assistant_messages(&text);
        assert_eq!(state, *exp_state, "detect_state mismatch for {file}");
        assert_eq!(count, *exp_count, "assistant count mismatch for {file}");
    }
}

/// The think-gap relay: during `thinking` the spinner line is returned (web shows the
/// same shimmer as the terminal); during `responding` it is `None` (we stream the body
/// instead, never a stale spinner). Guards the duplicate-of-last-message regression.
#[test]
fn spinner_line_only_during_think_gap() {
    let parser = select_parser("claude-code").expect("claude-code parser");
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");

    let thinking = String::from_utf8_lossy(
        &std::fs::read(dir.join("claude_2.1.x_thinking.txt")).expect("thinking fixture"),
    )
    .into_owned();
    let spin = parser
        .extract_spinner_line(&thinking)
        .expect("spinner line present while thinking");
    assert!(
        spin.contains("Thinking") && spin.contains('…'),
        "expected the active spinner verb line, got {spin:?}"
    );

    let responding = String::from_utf8_lossy(
        &std::fs::read(dir.join("claude_2.1.x_responding.txt")).expect("responding fixture"),
    )
    .into_owned();
    assert_eq!(
        parser.extract_spinner_line(&responding),
        None,
        "must not relay a spinner once the response is rendering"
    );
}
