//! Parser parity regression test. Locks the Rust port to the same results the
//! Python parser (`lit-bridge/parsers/claude/v2_1.py`) produces on its own validated
//! capture corpus. Fixtures copied from `lit-bridge/tests/captures/`.
//!
//! Expected values were generated by running the Python parser over these exact files
//! (see scripts/classify_all.py). If Anthropic changes the TUI and both parsers are
//! re-validated, regenerate these expectations.

use std::path::Path;

use lit_bridge_rs::parser::{select_parser, TuiParser};

/// (fixture, expected detect_state, expected count_assistant_messages)
const EXPECTED: &[(&str, &str, usize)] = &[
    ("claude_2.1.x_dialog.txt", "dialog", 0),
    ("claude_2.1.x_idle.txt", "idle", 1),
    ("claude_2.1.x_responding.txt", "responding", 4),
    ("claude_2.1.x_thinking.txt", "thinking", 1),
    ("claude_2.1.x_tool_use.txt", "idle", 2),
];

#[test]
fn parser_matches_python_oracle() {
    let parser = select_parser("claude-code").expect("claude-code parser");
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    for (file, exp_state, exp_count) in EXPECTED {
        let bytes = std::fs::read(dir.join(file)).expect("fixture present");
        let text = String::from_utf8_lossy(&bytes);
        let state = parser.detect_state(&text).as_str();
        let count = parser.count_assistant_messages(&text);
        assert_eq!(state, *exp_state, "detect_state mismatch for {file}");
        assert_eq!(count, *exp_count, "assistant count mismatch for {file}");
    }
}

/// Regression for the thinking-first streaming stall: the "esc to interrupt" hint is on
/// screen during BOTH thinking and talking, so it can't classify the turn on its own. Once
/// the model finishes thinking (`✻ Thought for Ns`) and starts rendering prose (an active
/// `●` bullet), the turn is `responding` — even though the interrupt hint is still shown.
/// Before the fix, `has_interrupt` short-circuited to `thinking` for the whole generation,
/// so the scrape-stream gate (which opens only on `responding`) never opened and nothing
/// streamed to the webapp until the final JSONL dump.
#[test]
fn thinking_first_talking_phase_is_responding() {
    let parser = select_parser("claude-code").expect("claude-code parser");
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let cap = String::from_utf8_lossy(
        &std::fs::read(dir.join("claude_2.1.x_thinking_first_talking.txt"))
            .expect("thinking-first-talking fixture"),
    )
    .into_owned();
    assert_eq!(
        parser.detect_state(&cap).as_str(),
        "responding",
        "an active response bullet must read as responding even while 'esc to interrupt' shows"
    );
    // And we must NOT relay a stale spinner once prose is rendering.
    assert_eq!(parser.extract_spinner_line(&cap), None);
}

/// The think-gap relay: during `thinking` the spinner line is returned (web shows the
/// same shimmer as the terminal); during `responding` it is `None` (we stream the body
/// instead, never a stale spinner). Guards the duplicate-of-last-message regression.
#[test]
fn spinner_line_only_during_think_gap() {
    let parser = select_parser("claude-code").expect("claude-code parser");
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");

    let thinking = String::from_utf8_lossy(
        &std::fs::read(dir.join("claude_2.1.x_thinking.txt")).expect("thinking fixture"),
    )
    .into_owned();
    let spin = parser
        .extract_spinner_line(&thinking)
        .expect("spinner line present while thinking");
    assert!(
        spin.contains("Thinking") && spin.contains('…'),
        "expected the active spinner verb line, got {spin:?}"
    );

    let responding = String::from_utf8_lossy(
        &std::fs::read(dir.join("claude_2.1.x_responding.txt")).expect("responding fixture"),
    )
    .into_owned();
    assert_eq!(
        parser.extract_spinner_line(&responding),
        None,
        "must not relay a spinner once the response is rendering"
    );
}

/// Regression: transient nags the TUI sprays below the spinner (npm auto-update
/// warning, `⎿ Tip:` lines) must not poison the bottom-up spinner scan. Before the
/// fix, `extract_spinner_line` bailed on the first unrecognized line and returned
/// None, so the real verb (`✶ Julienning…`) never relayed and the web fell back to
/// throbbing dots. See bridge-rs-evt log 2026-06-24: 40 polls, all spinner=false,
/// despite a visible verb.
#[test]
fn spinner_survives_trailing_nags() {
    let parser = select_parser("claude-code").expect("claude-code parser");

    // Spinner present, with chrome + nags stacked below it.
    let with_nags = "\
● Some earlier response text that has already streamed.

  Running 1 shell command…
✶ Julienning… (2m 55s · ↓ 10.1k tokens)
  ⎿  Tip: Use /btw to ask a quick side question without interrupting Claude
─────────────────────────────────────────
❯
─────────────────────────────────────────
✘ Auto-update failed: no write permission to npm prefix · Run /doctor
";
    let spin = parser
        .extract_spinner_line(with_nags)
        .expect("spinner must be found despite trailing auto-update nag and Tip line");
    assert!(
        spin.contains("Julienning") && spin.contains('…'),
        "expected the active spinner verb line, got {spin:?}"
    );

    // No active spinner: a settled response bullet with the same nags below must
    // still read as "no think-gap" (None), not get confused by the nag lines.
    let settled = "\
● A fully rendered response with no active spinner.
─────────────────────────────────────────
❯
─────────────────────────────────────────
✘ Auto-update failed: no write permission to npm prefix · Run /doctor
";
    assert_eq!(
        parser.extract_spinner_line(settled),
        None,
        "a settled response must not yield a spinner just because nags trail it"
    );
}
